import * as THREE from 'three'
import type { BossDef, BossId, EnemyEntity } from './types'

export const BOSSES: Record<BossId, BossDef> = {
  fogking: {
    id: 'fogking',
    name: '게으름의 안개왕',
    title: 'Fog King of Sloth',
    intro: '움직이기 귀찮아하는 거대한 안개가 마지못해 일어난다.',
    hp: 620,
    speed: 1.1,
    dmg: 13,
    radius: 2.1,
    scale: 1,
    color: '#141821',
    accent: '#6a7f9e',
    patterns: ['puddles', 'slam', 'summon'],
    patternInterval: 3.4,
  },
  notif: {
    id: 'notif',
    name: '알림중독의 악귀',
    title: 'Fiend of Infinite Notifications',
    intro: '읽지 않은 알림 99+개가 형체를 얻었다.',
    hp: 880,
    speed: 1.9,
    dmg: 11,
    radius: 1.8,
    scale: 1,
    color: '#181030',
    accent: '#5ad0ff',
    patterns: ['burst', 'dash', 'summon', 'burst'],
    patternInterval: 3.0,
  },
  mirror: {
    id: 'mirror',
    name: '비교지옥의 거울',
    title: 'Mirror of Comparison Hell',
    intro: '거울 속의 당신이 당신보다 잘 사는 것처럼 보인다.',
    hp: 1050,
    speed: 1.5,
    dmg: 13,
    radius: 1.9,
    scale: 1,
    color: '#101a22',
    accent: '#c05aff',
    patterns: ['mirror', 'burst', 'slam', 'puddles'],
    patternInterval: 3.2,
  },
  asura: {
    id: 'asura',
    name: '카드값의 아수라',
    title: 'Asura of the Card Statement',
    intro: '여섯 개의 팔이 여섯 장의 청구서를 들고 있다.',
    hp: 1400,
    speed: 1.6,
    dmg: 15,
    radius: 2.3,
    scale: 1,
    color: '#1c0f0f',
    accent: '#ff8a3a',
    patterns: ['slam', 'rings', 'dash', 'puddles'],
    patternInterval: 3.0,
  },
  deadline: {
    id: 'deadline',
    name: '마감임박 수라장군',
    title: 'Deadline Shura General',
    intro: '시간의 압박이 갑옷을 입고 걸어온다. 남은 시간: 임박.',
    hp: 1650,
    speed: 2.0,
    dmg: 15,
    radius: 2.0,
    scale: 1,
    color: '#160a1c',
    accent: '#ff4a6a',
    patterns: ['dash', 'burst', 'rings', 'haste', 'slam'],
    patternInterval: 2.8,
  },
}

let nextBossId = 100000

export function makeBoss(id: BossId, scaleMult: number, time: number): EnemyEntity {
  const def = BOSSES[id]
  const hp = Math.round(def.hp * scaleMult)
  return {
    id: nextBossId++,
    kind: 'japnyeom',
    boss: id,
    pos: new THREE.Vector3(0, 0, -8),
    vel: new THREE.Vector3(),
    knock: new THREE.Vector3(),
    facing: 0,
    hp,
    maxHp: hp,
    radius: def.radius * (0.7 + 0.3 * scaleMult),
    speed: def.speed,
    dmg: Math.round(def.dmg * (0.7 + 0.3 * scaleMult)),
    su: 60,
    scale: def.scale * (0.7 + 0.3 * scaleMult),
    color: def.color,
    eyeColor: def.accent,
    state: 'intro',
    stateT: 0,
    hitT: -10,
    spawnT: time,
    dying: false,
    dieT: 0,
    slowUntil: 0,
    staggerUntil: 0,
    touchCd: 0,
    shootCd: 2,
    orbitDir: 1,
    patternIdx: 0,
    patternT: 0,
    pattern: 'idle',
    hasteMult: 1,
    volleys: 0,
  }
}
