import * as THREE from 'three'
import type { EnemyEntity, EnemyKindDef, EnemyKindId } from './types'

export const ENEMY_KINDS: Record<EnemyKindId, EnemyKindDef> = {
  japnyeom: {
    id: 'japnyeom',
    name: '잡념 덩어리',
    hp: 42,
    speed: 2.1,
    dmg: 8,
    radius: 0.7,
    scale: 1,
    color: '#181820',
    eyeColor: '#ff4a3a',
    su: 6,
    ai: 'melee',
  },
  mirugi: {
    id: 'mirugi',
    name: '미루기의 망령',
    hp: 58,
    speed: 1.7,
    dmg: 12,
    radius: 0.75,
    scale: 1.15,
    color: '#141c22',
    eyeColor: '#ffb03a',
    su: 9,
    ai: 'dasher',
  },
  allim: {
    id: 'allim',
    name: '알림중독 귀신',
    hp: 46,
    speed: 2.4,
    dmg: 9,
    radius: 0.65,
    scale: 0.95,
    color: '#1a1426',
    eyeColor: '#5ad0ff',
    su: 10,
    ai: 'ranged',
  },
  bigyo: {
    id: 'bigyo',
    name: '비교심의 그림자',
    hp: 52,
    speed: 3.2,
    dmg: 10,
    radius: 0.65,
    scale: 0.95,
    color: '#101820',
    eyeColor: '#c05aff',
    su: 11,
    ai: 'circler',
  },
  shadow: {
    id: 'shadow',
    name: '그림자 분신',
    hp: 74,
    speed: 3.4,
    dmg: 13,
    radius: 0.7,
    scale: 1.05,
    color: '#0a0a10',
    eyeColor: '#ff3a6a',
    su: 14,
    ai: 'shadow',
  },
}

let nextId = 1

export function makeEnemy(
  kind: EnemyKindId,
  x: number,
  z: number,
  mult: number,
  time: number,
): EnemyEntity {
  const def = ENEMY_KINDS[kind]
  return {
    id: nextId++,
    kind,
    boss: null,
    pos: new THREE.Vector3(x, 0, z),
    vel: new THREE.Vector3(),
    knock: new THREE.Vector3(),
    facing: 0,
    hp: Math.round(def.hp * mult),
    maxHp: Math.round(def.hp * mult),
    radius: def.radius,
    speed: def.speed,
    dmg: Math.round(def.dmg * Math.sqrt(mult)),
    su: def.su,
    scale: def.scale,
    color: def.color,
    eyeColor: def.eyeColor,
    state: 'spawn',
    stateT: 0,
    hitT: -10,
    spawnT: time,
    dying: false,
    dieT: 0,
    slowUntil: 0,
    staggerUntil: 0,
    touchCd: 0,
    shootCd: 1.5 + Math.random() * 1.5,
    orbitDir: Math.random() > 0.5 ? 1 : -1,
    patternIdx: 0,
    patternT: 0,
    pattern: 'idle',
    hasteMult: 1,
    volleys: 0,
  }
}
