import type { StageDef } from './types'

export const STAGES: StageDef[] = [
  {
    id: 1,
    key: 'dawn_temple',
    name: '새벽 법당',
    nameEn: 'Dawn Sanctum',
    desc: '향 연기가 낮게 깔린 첫 수행처. 잡념이 모여들기 시작한다.',
    bg: '#171008',
    fog: '#2a1c0c',
    fogDensity: 0.028,
    ambient: '#ffb36b',
    ambientIntensity: 0.55,
    sun: '#ffca7a',
    sunIntensity: 1.6,
    ground: '#4a3018',
    groundEmissive: '#241207',
    rim: '#e8b25a',
    accent: '#ff9a3d',
    deco: 'temple',
    waves: [
      { spawns: [{ kind: 'japnyeom', count: 3 }] },
      { spawns: [{ kind: 'japnyeom', count: 4 }, { kind: 'mirugi', count: 1 }] },
    ],
    boss: 'fogking',
    bossScale: 0.55,
    enemyMult: 0.85,
    rewardSu: 120,
    rewardGong: 2,
  },
  {
    id: 2,
    key: 'rain_temple',
    name: '비 오는 산사',
    nameEn: 'Rainfall Monastery',
    desc: '푸른 안개 속, 젖은 돌바닥이 낮게 운다. 미루기의 망령이 배회한다.',
    bg: '#0a1016',
    fog: '#12202c',
    fogDensity: 0.04,
    ambient: '#5b7f9e',
    ambientIntensity: 0.6,
    sun: '#89b4d9',
    sunIntensity: 1.0,
    ground: '#1c2a35',
    groundEmissive: '#0a1420',
    rim: '#6fb6d9',
    accent: '#7fd0ff',
    deco: 'rain',
    waves: [
      { spawns: [{ kind: 'japnyeom', count: 3 }, { kind: 'mirugi', count: 2 }] },
      { spawns: [{ kind: 'mirugi', count: 3 }, { kind: 'japnyeom', count: 3 }] },
      { spawns: [{ kind: 'mirugi', count: 2 }, { kind: 'allim', count: 2 }] },
    ],
    boss: 'fogking',
    bossScale: 1,
    enemyMult: 1,
    rewardSu: 220,
    rewardGong: 4,
  },
  {
    id: 3,
    key: 'moon_pond',
    name: '달빛 연못',
    nameEn: 'Moonlit Pond',
    desc: '수면 위로 달이 두 개. 하나는 하늘에, 하나는 번뇌의 눈 속에.',
    bg: '#060a18',
    fog: '#0b1230',
    fogDensity: 0.032,
    ambient: '#8ea6ff',
    ambientIntensity: 0.65,
    sun: '#cfe0ff',
    sunIntensity: 1.2,
    ground: '#0e1836',
    groundEmissive: '#0a1030',
    rim: '#a8c4ff',
    accent: '#cfe0ff',
    deco: 'pond',
    waves: [
      { spawns: [{ kind: 'allim', count: 3 }, { kind: 'japnyeom', count: 2 }] },
      { spawns: [{ kind: 'allim', count: 3 }, { kind: 'bigyo', count: 2 }] },
      { spawns: [{ kind: 'bigyo', count: 3 }, { kind: 'allim', count: 2 }, { kind: 'mirugi', count: 2 }] },
    ],
    boss: 'notif',
    bossScale: 1,
    enemyMult: 1.05,
    rewardSu: 340,
    rewardGong: 6,
  },
  {
    id: 4,
    key: 'corridor',
    name: '번뇌의 회랑',
    nameEn: 'Corridor of Kleshas',
    desc: '검붉은 기둥 사이로 나의 그림자가 나를 노려본다.',
    bg: '#0d0508',
    fog: '#1c0709',
    fogDensity: 0.045,
    ambient: '#8a3030',
    ambientIntensity: 0.55,
    sun: '#ff6a4a',
    sunIntensity: 0.9,
    ground: '#170a0d',
    groundEmissive: '#200608',
    rim: '#ff5a45',
    accent: '#ff8a5a',
    deco: 'corridor',
    waves: [
      { spawns: [{ kind: 'bigyo', count: 3 }, { kind: 'mirugi', count: 3 }] },
      { spawns: [{ kind: 'shadow', count: 2 }, { kind: 'allim', count: 3 }] },
      { spawns: [{ kind: 'shadow', count: 3 }, { kind: 'bigyo', count: 3 }] },
    ],
    boss: 'mirror',
    bossScale: 1,
    enemyMult: 1.15,
    rewardSu: 480,
    rewardGong: 8,
  },
  {
    id: 5,
    key: 'bell_tower',
    name: '구름 위 종루',
    nameEn: 'Belfry Above Clouds',
    desc: '발 아래는 구름의 바다. 카드값의 아수라가 청구서를 들고 온다.',
    bg: '#1a2138',
    fog: '#2c3a5c',
    fogDensity: 0.03,
    ambient: '#9fb4e8',
    ambientIntensity: 0.75,
    sun: '#ffe9c4',
    sunIntensity: 1.7,
    ground: '#3a4668',
    groundEmissive: '#1c2340',
    rim: '#ffd98a',
    accent: '#ffe9c4',
    deco: 'sky',
    waves: [
      { spawns: [{ kind: 'mirugi', count: 4 }, { kind: 'allim', count: 3 }] },
      { spawns: [{ kind: 'bigyo', count: 4 }, { kind: 'shadow', count: 2 }] },
      { spawns: [{ kind: 'shadow', count: 2 }, { kind: 'allim', count: 4 }, { kind: 'mirugi', count: 3 }] },
    ],
    boss: 'asura',
    bossScale: 1,
    enemyMult: 1.25,
    rewardSu: 650,
    rewardGong: 10,
  },
  {
    id: 6,
    key: 'cosmos',
    name: '우주 만다라',
    nameEn: 'Cosmic Mandala',
    desc: '별들이 회전하는 최후의 법계. 마감은 이곳까지 쫓아왔다.',
    bg: '#02030c',
    fog: '#070a20',
    fogDensity: 0.022,
    ambient: '#8a7fff',
    ambientIntensity: 0.7,
    sun: '#cabfff',
    sunIntensity: 1.3,
    ground: '#0a0a24',
    groundEmissive: '#14103a',
    rim: '#b8a8ff',
    accent: '#e0c8ff',
    deco: 'cosmos',
    waves: [
      { spawns: [{ kind: 'shadow', count: 3 }, { kind: 'bigyo', count: 3 }] },
      { spawns: [{ kind: 'allim', count: 4 }, { kind: 'mirugi', count: 4 }] },
      { spawns: [{ kind: 'shadow', count: 3 }, { kind: 'allim', count: 3 }, { kind: 'bigyo', count: 3 }] },
    ],
    boss: 'deadline',
    bossScale: 1,
    enemyMult: 1.35,
    rewardSu: 900,
    rewardGong: 14,
  },
]

export function stageById(id: number): StageDef {
  return STAGES.find((s) => s.id === id) ?? STAGES[0]
}
